<?php
/**
 * Created by PhpStorm.
 * User: maltsev
 * Date: 20.10.2017
 * Time: 11:28
 */

namespace common\modules\sitemap\components;

use Yii;
use yii\base\Component;
use common\modules\sitemap\models\GenerateUrls;
use common\modules\sitemap\models\ItemConfigure;
use common\modules\sitemap\models\XmlGenerate;

class SitemapComponent extends Component
{
    public $pathSitemapFiles = '@webroot/sitemaps';
    public $timeLive = 3600 * 24 * 5; // 5 days
    public $maxMapRecords = 50000;
    public $runtimePath = '@app/runtime';
    public $models;
    public $staticUrl;
    public $xmlns = 'http://www.sitemaps.org/schemas/sitemap/0.9';
    public $domain = '';
    public $baseNameFile = 'sitemap';
    public $defaultPriority = '0.7';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (strpos($this->pathSitemapFiles, '@') === 0) {
            $this->pathSitemapFiles = Yii::getAlias($this->pathSitemapFiles);
        }
    }

    public function isTimeout()
    {
        $cacheComponent = Yii::$app->getCache();
        $keyCache = 'SitemapKeyCache';

        if ($cacheComponent) {
            if ($cacheComponent->exists($keyCache)) {
                return false;
            } else {
                $cacheComponent->set($keyCache, 'ok', $this->timeLive);
                return true;
            }
        } else {
            return true;
        }
    }

    public function createSitemaps()
    {
        $xmlModel = new XmlGenerate();

        // default url
        $xmlModel->appendTo(
            ItemConfigure::createObjectUrls($this->staticUrl)
        );

        if (!empty($this->models)) {
            $models = new GenerateUrls();
            $models->setModels($this->models);

            $result = $models->run();

            if ($result->valid()) {
                foreach ($result as $urls) {
                    $xmlModel->appendTo($urls);
                }
            }
        }

        $xmlModel->createFile();
    }

    public function renderWrapper()
    {
        return (new XmlGenerate(false))->wrapper($this->domain);
    }
}