<?php
/**
 * Created by PhpStorm.
 * User: maltsev
 * Date: 20.10.2017
 * Time: 11:27
 */

namespace common\modules\sitemap\controllers;

use Yii;
use yii\base\Controller;
use yii\web\Response;

class DefaultController extends Controller
{
    /**
     * @property SitemapComponent
     */
    private $component;

    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->component = Yii::$app->sitemapComponent;

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if ($this->component->isTimeout()) {
            $this->component->createSitemaps();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Action /sitemap.xml
     *
     * @return string
     */
    public function actionIndex()
    {
        @header('Content-type: text/xml; charset: UTF-8');
        Yii::$app->response->format = Response::FORMAT_RAW;

        return Yii::$app->sitemapComponent->renderWrapper();
    }
}